version: 0.0
os: linux
files:
  - source: /
    destination: /var/app
file_exists_behavior: OVERWRITE
permissions:
  - object: /var/app
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 1000
      runas: root

